TM-8601 Provide documentation for data-disable-delay attribute (16.0)
PiwikPRO/PPMS-PublicDocs pull request #703
Opened 2021-10-28 10:12 UTC by musialp

Provide documentation for data-disable-delay attribute (skip link tracking)

2021-11-02 12:22 UTC, zawias-pro requested changes

2021-11-02 12:22 UTC, zawias-pro commented on tag_manager/skip_link_tracking.rst
> +to execute before the redirect happens. That is why, our container is equiped
```suggestion
to execute before the redirect happens. That is why our container is equipped
```

2021-11-02 12:22 UTC, zawias-pro commented on tag_manager/skip_link_tracking.rst
> +container. Once the anchor element is clicked and the aformentioned attribute
```suggestion
container. Once the anchor element is clicked and the aforementioned attribute
```

2021-11-02 12:22 UTC, zawias-pro commented on tag_manager/skip_link_tracking.rst
> +#.  Lets assume that your Tag Manager setup includes a `Custom code (async)` tag
```suggestion
#.  Let's assume that your Tag Manager setup includes a `Custom code (async)` tag
```

2021-11-02 12:22 UTC, zawias-pro commented on tag_manager/skip_link_tracking.rst
> +    trigger` assigned to said tag
```suggestion
    trigger` assigned to the said tag.
```

2021-11-02 15:24 UTC, musialp commented on tag_manager/skip_link_tracking.rst
> +to execute before the redirect happens. That is why, our container is equiped
Done

2021-11-02 15:24 UTC, musialp commented on tag_manager/skip_link_tracking.rst
> +container. Once the anchor element is clicked and the aformentioned attribute
Done

2021-11-02 15:24 UTC, musialp commented on tag_manager/skip_link_tracking.rst
> +#.  Lets assume that your Tag Manager setup includes a `Custom code (async)` tag
Done

2021-11-02 15:24 UTC, musialp commented on tag_manager/skip_link_tracking.rst
> +    trigger` assigned to said tag
Done

2021-11-02 15:28 UTC, zawias-pro approved these changes

2021-11-03 06:05 UTC, JacekClearcode approved these changes

2021-11-03 06:06 UTC, merged