PPPSYS-39200 Add available consent types to developers documentation
PiwikPRO/PPMS-PublicDocs pull request #987
Opened 2023-03-07 14:08 UTC by archi-tektur

2023-03-07 15:03 UTC, kororokke commented
Master branch is the target?

2023-03-08 07:40 UTC, archi-tektur commented
@kororokke If I understand this correctly, yes. It's not related to any changes in any release, just adding some explanation about exact values an API user can use.

2023-03-08 12:02 UTC, musialp reviewed
@archi-tektur I was wondering if maybe we could solve this in a similar manner as the custom dimensions object is handled [here](https://developers.piwik.pro/en/latest/data_collection/web/javascript_tracking_client/api.html#custom-events), so put the list in a separate section and link to it where needed. What do you think?

2023-03-09 16:16 UTC, archi-tektur commented
@musialp You can check it out if it's working fine for you now :)

2023-03-10 12:29 UTC, musialp requested changes

2023-03-10 12:29 UTC, musialp commented on consent_manager/js_api/commands.rst
> +Compliance types reference
or
```suggestion
Available consent types
```

2023-03-10 12:29 UTC, musialp commented on consent_manager/js_api/commands.rst
> +Compliance types reference
Compliance is only used in command names for compatibility reason. Whenever we refer to those particular values we call them `consent types`

2023-03-10 12:29 UTC, musialp commented on consent_manager/js_api/commands.rst
> -    Where ``consent.analytics`` is consent type and status indicate:
This was removed for `Set compliance settings` but stayed for `Get compliance settings`. IMO it should stay for both as the available status values are different.

2023-03-10 12:29 UTC, musialp commented on consent_manager/js_api/commands.rst
> +Compliance types reference
You mentioned that it is bothering you, that it looks like another command and I agree. What do you think about putting it as a top level section? Same as `Introduction` and `Commands`?

2023-03-10 14:49 UTC, archi-tektur commented on consent_manager/js_api/commands.rst
> +        .. note::
fixed

2023-03-10 14:59 UTC, archi-tektur commented on consent_manager/js_api/commands.rst
> +Compliance types reference
Done just like you said it - looks good!

2023-03-10 15:00 UTC, archi-tektur commented on consent_manager/js_api/commands.rst
> +        * ``1``  - user has approved the consent
fixed

2023-03-13 11:31 UTC, musialp commented on consent_manager/js_api/reference.rst
> +
```suggestion
```

2023-03-13 11:42 UTC, archi-tektur commented on consent_manager/js_api/reference.rst
> +
done

2023-03-13 11:42 UTC, musialp approved these changes

2023-03-13 11:44 UTC, archi-tektur commented
@RomanSek @kororokke team review is done, please check it out and review if you have a moment

2023-03-14 06:19 UTC, kororokke approved these changes

2023-03-14 08:19 UTC, merged